name: flutter_bluesky_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ###  API  ###
  bluesky: ^0.8.9

  ###  State Management  ###
  flutter_riverpod: any
  riverpod_annotation: any
  freezed_annotation: any
  json_serializable: any

  ###  Routing  ###
  go_router: any

  ###  DB  ###
  shared_preferences: any

  ###  Icon  ###
  iconsax: any
  font_awesome_flutter: any

  ###  Util  ###
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  ###  Lint  ###
  very_good_analysis: any
  custom_lint: any
  riverpod_lint: any

  ###  Generator  ###
  riverpod_generator: any
  build_runner: any
  freezed: any

  ###  Splash/App Icon  ###
  flutter_launcher_icons: any
  flutter_native_splash: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/bluesky.jpeg"

flutter_native_splash:
  background_image: "assets/images/bluesky.jpeg"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/