name: flutter_bluesky_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ###  API  ###
  bluesky: ^0.8.9

  ###  State Management  ###
  flutter_riverpod: any
  riverpod_annotation: any
  freezed_annotation: any
  json_serializable: any

  ###  Routing  ###
  go_router: any

  ###  DB  ###
  shared_preferences: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any
  custom_lint: any
  riverpod_lint: any
  riverpod_generator: any
  build_runner: any
  freezed: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/