name: flutter_bluesky_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ###  API  ###
  bluesky: ^0.8.9
  ###  State Management  ###
  flutter_riverpod: any
  ###  Routing  ###
  go_router: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any

flutter:
  uses-material-design: true
